image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

environment:
  global:
    - SELENIDE_PAGE_LOAD_STRATEGY: eager

install:
  - ps: [Environment]::SetEnvironmentVariable("SELENIDE_PAGE_LOAD_STRATEGY", $env:SELENIDE_PAGE_LOAD_STRATEGY, [System.EnvironmentVariableTarget]::Machine)

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true
